### PR TITLE
cbmcopy: Fixes for remote filename handling

### LINKED ISSUE #106: cbmcopy can’t specify drive for dual disk models (8050)
UPDATE 2: Now it DID write to unit 1. I really don't understand what the logic behind this is. Fact is, you can't specify the target drive when writing to the disc.

UPDATE: I was wrong, it is not random, it seems to be ALWAYS drive unit 0, which I guess makes more sense. So maybe we can add a drive selection somehow, to be able to also write to unit 1?

OLD TEXT: The cbmcopy tool uses a random drive in CBM 8050 and similar models. The files get copied fine, but sometimes end up on drive 0, sometimes on drive 1.

### PR DESCRIPTION
**Pull request by thierer**
These two commits should fix #106 and #107.

6cf5a832 limits filtering for the remote filename (introduced in 2937f54b) to cases when the filename is auto-generated from the local filename.

7a13a217 removes the 16 byte filename limit for both read and write except for the case when the remote filename is auto-generated for writing. I don't see why limiting the filename length would be needed, because as far as I can tell CBM DOS ignores extra filename characters anyway. And it hurts in the cases as discussed in #106 and #107 and even more so when working with a device which supports subdirectories, like the CMD HD.

With both commits applied, something like `cbmcopy -w -o "/subdir:fileinsubdir" 8 test.prg` works as intended, even though the filename includes a colon and is 20 characters in length, while with `cbmcopy -w 8 "test:2.prg"` the remote filename is still changed to `test 2` (`[Info] writing test:2.prg -> test 2,p,w`).

### CODE REVIEW

File: opencbm/cbmcopy/main.c [hunk 1]
```diff
@@ -488,8 +490,9 @@ int ARCH_MAINDECL main(int argc, char **argv)
                         {
                             if(output_name)
                             {
-                                strncpy(buf, output_name, 16);
-                                buf[16] = '\0';
+                                /* leave room for file type, mode and '\0'  */
+                                strncpy(buf, output_name, FN_BUFFER_SIZE-5);
```
Comment (spiro-trikaliotis) [inline opencbm/cbmcopy/main.c:494]: Why don't you use "sizeof buf" instead of "FN_BUFFER_SIZE"?

File: opencbm/cbmcopy/main.c [hunk 2]
```diff
@@ -30,6 +30,8 @@
 #include "statedebug.h"
 
 
+#define FN_BUFFER_SIZE 48
```
Comment (spiro-trikaliotis) [inline opencbm/cbmcopy/main.c:33]: I like that you change the constant to a define.
Better would be that the whole string handling is rewritten, but this is a story for another, bigger PR.

File: opencbm/cbmcopy/main.c [hunk 3]
```diff
@@ -569,8 +572,9 @@ int ARCH_MAINDECL main(int argc, char **argv)
             }
             else
             {
-                strncpy(buf, fname, 16);
-                buf[16] = '\0';
+                /* leave room for file type and '\0' */
+                strncpy(buf, fname, FN_BUFFER_SIZE-3);
```
Comment (spiro-trikaliotis) [inline opencbm/cbmcopy/main.c:576]: same here...

File: opencbm/cbmcopy/main.c [hunk 4]
```diff
@@ -569,8 +572,9 @@ int ARCH_MAINDECL main(int argc, char **argv)
...
+                buf[FN_BUFFER_SIZE-3] = '\0';
```
Comment (spiro-trikaliotis) [inline opencbm/cbmcopy/main.c:577]: and here.

**Review by spiro-trikaliotis — COMMENTED** [review]
Looks fine for me.

File: opencbm/cbmcopy/main.c (hunk 1 above)
Comment (thierer) [reply opencbm/cbmcopy/main.c]: Because the code didn't use a `sizeof` before, either :smiley: 

But sure, I changed it and pushed the new version.

File: opencbm/cbmcopy/main.c (hunk 2 above)
Comment (thierer) [reply opencbm/cbmcopy/main.c:33]: > Better would be that the whole string handling is rewritten

I agree, but I'm not sure I have enough motivation.

Comment (spiro-trikaliotis) [reply opencbm/cbmcopy/main.c:33]: Oh, that's ok. I did not expect you to do that!

**Review by spiro-trikaliotis — APPROVED** [review]
It's ok, thank you.
